version: 2

builds:
  # ==================== Linux 构建 ====================
  
  # Linux AMD64 (x86_64) - 最常用的服务器架构
  - id: linux-amd64
    env:
      - CGO_ENABLED=1
    main: ./cmd/server
    binary: nodepassdash
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X main.Version={{ .Version }}
    tags:
      - sqlite_omit_load_extension
      - sqlite_fts
      - sqlite_stat4
      
  # Linux ARM64 (aarch64) - 新款ARM服务器、树莓派4 64位
  - id: linux-arm64
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
    main: ./cmd/server
    binary: nodepassdash
    goos:
      - linux
    goarch:
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X main.Version={{ .Version }}
    tags:
      - sqlite_omit_load_extension
      - sqlite_fts
      - sqlite_stat4
      
  # Linux ARMv7 (hard-float) - 树莓派2/3/4 32位、大多数ARM设备
  - id: linux-armv7
    env:
      - CGO_ENABLED=1
      - CC=arm-linux-gnueabihf-gcc
    main: ./cmd/server
    binary: nodepassdash
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 7
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X main.Version={{ .Version }}
    tags:
      - sqlite_omit_load_extension
      - sqlite_fts
      - sqlite_stat4
      
  # Linux ARMv6 (soft-float) - 树莓派1、老款ARM设备
  - id: linux-armv6
    env:
      - CGO_ENABLED=1
      - CC=arm-linux-gnueabi-gcc
    main: ./cmd/server
    binary: nodepassdash
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 6
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X main.Version={{ .Version }}
    tags:
      - sqlite_omit_load_extension
      - sqlite_fts
      - sqlite_stat4

  # ==================== Windows 构建 ====================
      
  # Windows AMD64 - 主流Windows系统
  - id: windows-amd64
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
    main: ./cmd/server
    binary: nodepassdash
    goos:
      - windows
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X main.Version={{ .Version }}
    tags:
      - sqlite_omit_load_extension
      - sqlite_fts
      - sqlite_stat4
      
  # Windows 386 - 32位Windows系统
  - id: windows-386
    env:
      - CGO_ENABLED=1
      - CC=i686-w64-mingw32-gcc
    main: ./cmd/server
    binary: nodepassdash
    goos:
      - windows
    goarch:
      - 386
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X main.Version={{ .Version }}
    tags:
      - sqlite_omit_load_extension
      - sqlite_fts
      - sqlite_stat4

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm" }}armv{{ .Arm }}
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}hf{{ end }}
    # 包含额外文件到压缩包
    files:
      - README.md
      - LICENSE
    # 确保二进制文件在根目录，其他文件保持相对路径
    wrap_in_directory: false

release:
  # 自动检测预发布版本 (包含 alpha, beta, rc 等)
  prerelease: auto
  # 发布名称模板
  name_template: "NodePassDash {{ .Version }}"
  # 允许替换已存在的发布
  replace_existing_draft: true
  # 发布说明
  header: |
    # NodePassDash v3.2.0 更新日志
    
    ## 版本信息
    - **版本号**: v3.2.0
    - **核心适配**: NodePass Core 1.11
    - **依赖更新**: HeroUI 2.8.5、Tailwind CSS 4
  
    ---
  
    ## 📋 更新概述
    
    本次更新重点围绕**服务管理体系**的全面升级，新增服务管理模块，优化实例管理流程，增强主控功能，并修复多项已知问题。主要亮点包括：
  
    - ✨ **新增服务管理模块**：全新的服务组装、管理和监控体系
    - 🔧 **实例管理增强**：新增多项配置参数，优化创建/编辑流程
    - 📊 **数据展示优化**：新增排序、统计图表等功能
    - 🐛 **问题修复**：解决重命名409错误、mode参数缺失等问题
  
    ---
    
    ## 🆕 新增功能
    
    ### 1. 服务管理模块（核心功能）
    
    #### 1.1 服务管理页面
    - **导航栏新增**：服务管理菜单入口
    - **首页仪表盘**：新增服务数量统计显示
    - **服务创建**：
      - 全新的服务创建功能（原实例管理的场景创建功能迁移至此）
      - 服务组装功能：支持将已有实例组装为服务
    - **服务列表**：
      - 卡片式布局展示服务信息（名称、类型、入口/出口、流量等）
      - 支持拖拽排序
      - 实例操作：启动、停止、重启、删除
      - 服务操作：同步、重命名、解散
    
    #### 1.2 服务详情页
      采用全新的滑动页面布局设计，提供多维度服务信息展示：
      
      **功能特性**：
    - **实例批量操作**：
      - 启动/停止/重启：批量操作服务内所有实例
      - 删除：删除服务关联实例及本地服务数据
    - **服务管理操作**：
      - 同步：更新客户端与服务端数据，刷新服务信息
      - 重命名：修改服务名称
      - 解散：取消客户端与服务端的关联标记
    - **监控与分析**：
      - 流量信息：实时流量数据及历史统计图表
      - 网络质量：延迟、连接数监控
      - 关联跳转：支持跳转至服务端/客户端详情页
    - **调试工具**：
      - 新增网络连通性测试功能
      - 新增SSE调试页面（支持同时调试服务端和客户端）
    
    ### 2. 实例管理增强
    
    #### 2.1 创建/编辑实例
      **新增配置参数**：
    - 监听类型
    - 负载均衡地址
    - QUIC 支持
    - Dial 配置
    - DNS 设置
    - 排序权重
      
      **优化改进**：
    - 全新的表单布局UI
    - 优化模态窗内部逻辑
    - 优化编辑表单数据传递逻辑
    - 重命名功能改进：避免409错误
    - 权重修改逻辑优化：避免冲突错误
    
    #### 2.2 实例列表
    - **新增排序功能**：支持按 ID、权重、类型、名称、主控、状态、服务进行升序/降序排序
    - **默认排序调整**：列表默认按权重排序
    - **API优化**：简化列表数据获取逻辑
    
    #### 2.3 实例详情页
      **新增显示信息**：
    - 监听类型
    - QUIC 状态
    - Dial 配置
    - DNS 配置
    - 排序权重
    - 关联服务（支持跳转至服务详情页）
    - 多目标地址展示
      
      **功能优化**：
    - Tag 设置：优化交互逻辑，适配新的 `meta.tags` 数据结构
    - 可交互项新增白色圆点提示标识
    - URL展示：默认从"命令URL"调整为"配置URL"
    - 网络质量：
      - 优化连接池相关提示文案
      - 优化0ms延迟的显示逻辑
    - 连通性测试：支持多目标地址选择（需配置负载均衡）
    
    ### 3. 主控管理增强
      
      **数据结构**：
    - 新增 `hostname` 字段：解析主控链接地址，便于后续使用
      
      **主控列表**：
    - 支持按名称排序
    - Beta版核心增强提醒
      
      **主控详情页**：
    - 移除实验性功能判断
    - 直接展示主控机状态信息
    
    ---
    
    ## 🔧 优化改进
    
    ### 代码层面
    - 优化实例创建/修改API逻辑，简化代码结构
    - 移除陈年冗余代码
    - 修复多处逻辑问题
    
    ### 用户体验
    - 个性化设置：移除新手模式设置选项
    - 弃用旧版创建实例页面
    
    ### 依赖更新
    - 升级 HeroUI 至 2.8.5
    - 修复 Tailwind CSS 4 的部分样式兼容问题
    
    ---
    
    ## 🐛 问题修复
      
      | 问题 | 修复说明 |
      |------|----------|
      | 实例重命名409错误 | 优化重命名逻辑，避免命名冲突 |
      | 权重修改冲突 | 改进权重更新机制 |
      | 服务创建缺少mode参数 | 修复旧版服务创建流程的参数传递问题 |
      | 样式兼容问题 | 适配 Tailwind CSS 4 |
      | 实例信息相关值过长问题 | 修复server的key和cert以及服务名称过长显示的问题 |
    
    ---
    
    ## 🔄 迁移说明
    
    1. **场景创建功能迁移**：原实例管理中的"场景创建"功能已迁移至服务管理，请从服务管理页面创建新服务
    2. **旧版创建页面**：已弃用，建议使用新版创建/编辑模态窗
    3. **新手模式**：该选项已从个性化设置中移除
    
    ---
    
    ## 📌 注意事项
    
    - 本版本需配合 NodePass Core 1.11 使用
    - 服务管理为全新模块，建议详细阅读相关文档
    - 升级后建议检查已有实例的配置参数是否正常
  footer: |
    
    ### 📥 下载说明
    - **Linux x86_64**: `nodepassdash_Linux_x86_64.tar.gz` (服务器推荐)
    - **Linux ARM64**: `nodepassdash_Linux_arm64.tar.gz` (树莓派4 64位、ARM服务器)
    - **Linux ARMv7**: `nodepassdash_Linux_armv7hf.tar.gz` (树莓派2/3/4 32位)
    - **Linux ARMv6**: `nodepassdash_Linux_armv6.tar.gz` (树莓派1、老设备)
    - **Windows 64位**: `nodepassdash_Windows_x86_64.zip`
    - **Windows 32位**: `nodepassdash_Windows_i386.zip`
    
    ### 🐳 Docker 镜像
    ```bash
    docker pull ghcr.io/nodepassproject/nodepassdash:{{ .Version }}
    ```
    
    ### 🔧 使用说明
    1. 下载对应架构的二进制文件
    2. 解压后直接运行 `./nodepassdash`（无需外部依赖）
    3. 默认监听 `http://localhost:3000`
    
    ### 📝 部署说明
    - **单文件部署**: 只需要一个可执行文件即可运行
    - **自动初始化**: 程序会自动创建所需的文件和目录
    - **数据持久化**: 数据库文件保存在 `db/database.db`