version: 2

builds:
  # ==================== Linux 构建 ====================
  
  # Linux AMD64 (x86_64) - 最常用的服务器架构
  - id: linux-amd64
    env:
      - CGO_ENABLED=1
    main: ./cmd/server
    binary: nodepassdash
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X main.Version={{ .Tag }}
    tags:
      - sqlite_omit_load_extension
      
  # Linux ARM64 (aarch64) - 新款ARM服务器、树莓派4 64位
  - id: linux-arm64
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
    main: ./cmd/server
    binary: nodepassdash
    goos:
      - linux
    goarch:
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X main.Version={{ .Tag }}
    tags:
      - sqlite_omit_load_extension
      
  # Linux ARMv7 (hard-float) - 树莓派2/3/4 32位、大多数ARM设备
  - id: linux-armv7
    env:
      - CGO_ENABLED=1
      - CC=arm-linux-gnueabihf-gcc
    main: ./cmd/server
    binary: nodepassdash
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 7
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X main.Version={{ .Tag }}
    tags:
      - sqlite_omit_load_extension
      
  # Linux ARMv6 (soft-float) - 树莓派1、老款ARM设备
  - id: linux-armv6
    env:
      - CGO_ENABLED=1
      - CC=arm-linux-gnueabi-gcc
    main: ./cmd/server
    binary: nodepassdash
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 6
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X main.Version={{ .Tag }}
    tags:
      - sqlite_omit_load_extension

  # ==================== Windows 构建 ====================
      
  # Windows AMD64 - 主流Windows系统
  - id: windows-amd64
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
    main: ./cmd/server
    binary: nodepassdash
    goos:
      - windows
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X main.Version={{ .Tag }}
    tags:
      - sqlite_omit_load_extension
      
  # Windows 386 - 32位Windows系统
  - id: windows-386
    env:
      - CGO_ENABLED=1
      - CC=i686-w64-mingw32-gcc
    main: ./cmd/server
    binary: nodepassdash
    goos:
      - windows
    goarch:
      - 386
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X main.Version={{ .Tag }}
    tags:
      - sqlite_omit_load_extension

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm" }}armv{{ .Arm }}
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}hf{{ end }}
    # 包含额外文件到压缩包
    files:
      - README.md
      - LICENSE
    # 确保二进制文件在根目录，其他文件保持相对路径
    wrap_in_directory: false

release:
  # 自动检测预发布版本 (包含 alpha, beta, rc 等)
  prerelease: auto
  # 发布名称模板
  name_template: "NodePassDash {{ .Tag }}"
  # 允许替换已存在的发布
  replace_existing_draft: true
  # 发布说明
  header: |
    ## NodePassDash {{ .Tag }}
    
    ### 主要：对核心1.4.x的适配
  
    ### Feature
    
    #### 主控
  
    - 主控列表支持显示版本号
    - 增加主控详情页显示系统等信息
  
    - 主控支持更改密钥
    
    #### 实例
  
    - 添加隧道时，如果tls和info选择了继承主控，会显示出主控的设定值(需主控版本为1.4.x)
    - 详情页 如果tls和info选择了继承主控，会显示出主控的设定值(需主控版本为1.4.x)
    - 添加隧道、快速创建、手搓创建、编辑隧道 适配密码参数(需主控版本为1.4.x)
    - 手搓实例 改进为可批量手搓
    - 详情页，显示 自动重启(需主控版本为1.4.x)，并可更改
    - 隧道管理列表增加流量统计列显示
    - 全局记住隧道管理列表的 隐藏/显示ip 的状态
    - 重命名实例的功能已支持同步所有主控（包括注册主控时的同步，更改重命名时的同步，创建实例时的同步，需主控版本为1.4.x）
    
    #### 其他
  
    - 增加启动时可通过参数--log-level设定控制台日志级别
    - 处理相关列表和页面的适配
    - 回收站列表也进行密码参数的适配，同时优化展开块的布局
    - 新增系统设置页
      - 支持手动版本检测
      - 账户设置cf/github占位
    
    ### Update
    
    #### 主控
  
    - 主控移除添加实例按钮
    - 移除主控页的回收站按钮功能
    
    #### 实例
  
    - 实例管理列表移动端布局隐藏多选按钮
    - 移除隧道名称唯一不可重复的检测
    - 更改 批量导出 label
    - 客户端的默认连接池数的默认显示
    - 创建实例 调整选择主控的卡片视图时的长度
    
    #### 其他
  
    - 优化仪表盘api主控视图
    - 导入数据适配原来的v1格式
    - 导出数据格式v2，舍弃tunnel的数据格式(因为1.4.x支持同步实例名)
    - 删除对报错404调用接口的适
    - 优化回收站的列表显示逻辑
    - 调整部分页面 && 修改部分按钮布局
    - 修改移动端navbar的布局，将menu toggle移到最左侧
    - 数据库字段变动
    - 优化重启的逻辑和效果
    - 优化创建的逻辑和效果
    
    ### Fix
  
    - 隧道筛选主控的下拉和主页的主控显示隧道数量异常问题
  
    - 平板竖屏看不到navbar的menu
    - SSE服务中的空指针解引用错误
    
    
  footer: |
    
    ### 📥 下载说明
    - **Linux x86_64**: `nodepassdash_Linux_x86_64.tar.gz` (服务器推荐)
    - **Linux ARM64**: `nodepassdash_Linux_arm64.tar.gz` (树莓派4 64位、ARM服务器)
    - **Linux ARMv7**: `nodepassdash_Linux_armv7hf.tar.gz` (树莓派2/3/4 32位)
    - **Linux ARMv6**: `nodepassdash_Linux_armv6.tar.gz` (树莓派1、老设备)
    - **Windows 64位**: `nodepassdash_Windows_x86_64.zip`
    - **Windows 32位**: `nodepassdash_Windows_i386.zip`
    
    ### 🐳 Docker 镜像
    ```bash
    docker pull ghcr.io/nodepassproject/nodepassdash:{{ .Tag }}
    ```
    
    ### 🔧 使用说明
    1. 下载对应架构的二进制文件
    2. 解压后直接运行 `./nodepassdash`（无需外部依赖）
    3. 首次运行会自动解压前端文件到 `dist/` 目录
    4. 默认监听 `http://localhost:3000`
    5. 首次运行会自动创建管理员账户
    
    ### 📝 部署说明
    - **单文件部署**: 只需要一个可执行文件即可运行
    - **自动初始化**: 程序会自动创建所需的文件和目录
    - **数据持久化**: 数据库文件保存在 `public/sqlite.db` 