-- 为端点表添加系统信息字段
ALTER TABLE "Endpoint" ADD COLUMN os TEXT DEFAULT '';
ALTER TABLE "Endpoint" ADD COLUMN arch TEXT DEFAULT '';
ALTER TABLE "Endpoint" ADD COLUMN ver TEXT DEFAULT '';
ALTER TABLE "Endpoint" ADD COLUMN log TEXT DEFAULT '';
ALTER TABLE "Endpoint" ADD COLUMN tls TEXT DEFAULT '';
ALTER TABLE "Endpoint" ADD COLUMN crt TEXT DEFAULT '';
ALTER TABLE "Endpoint" ADD COLUMN key_path TEXT DEFAULT ''; 